### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by CRuppert** [xamarin/Xamarin.Mobile#62]
@ermau @joelmartinez 
I would love to be able to take a dependency on this project for things like the camera, however there are several PRs that are 6+ months old, 21 open issues, also old, untouched etc.

I mean no disrespect, but I would love to know if the project is abandoned, if not, what the planned support is going forward.

Thank you!

**Comment by joelmartinez** [comment]
Hi @CRuppert ... you should probably take a look at https://github.com/xamarin/XamarinComponents :) there are many open source components there, including camera (look for the [Media](https://github.com/jamesmontemagno/Xamarin.Plugins/tree/master/Media) plugin).

Best of luck!
